services:

  willowcms:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:8080"
    environment:
      - REDIS_USERNAME=root #change this when building the image
      - REDIS_PASSWORD=root #cahnge this when building the image