services:

  willowcmstest:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - "6380:6379"
    volumes:
      - redis_prod_data:/data
    expose:
      - "6380"

volumes:
  mysql_prod_data:
  redis_prod_data:
