services:

  willowcms:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    environment:
      - WILLOW_ADMIN_USERNAME=admin
      - WILLOW_ADMIN_PASSWORD=password
      - WILLOW_ADMIN_EMAIL=admin@example.com
