services:

  willowcms:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:8080"
    depends_on:
      - mysql
    environment:
      - REDIS_USERNAME=root
      - REDIS_PASSWORD=root

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_prod_data:
  redis_prod_data:
