services:

  willowcms:
    build:
      context: .
      dockerfile: config/linode/Dockerfile
      args:
        WILLOW_VERSION: "1.0.23"
    ports: 
      - "443:443"
    volumes:
      - willowcms_uploads:/var/www/html/webroot/files
      - /certs/willowcms.app.pem:/certs/willowcms.app.pem
      - /certs/willowcms.app.key:/certs/willowcms.app.key
    # CHANGE THESE WHEN BUILDING THE IMAGE FOR PRODUCTION TO MATCH SECRETS
    environment:
      - REDIS_USERNAME=root
      - REDIS_PASSWORD=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=cms_user
      - DB_PASSWORD=password
      - DB_DATABASE=cms
      - REDIS_URL=redis://root:root@127.0.0.1:6379/0
      - SECURITY_SALT=389ur8934vn8934urnv89uidfvnhfg98vyhg785hvb7nghvbsdgvhsfbu
      - WILLOW_ADMIN_USERNAME=admin
      - WILLOW_ADMIN_PASSWORD=password
      - WILLOW_ADMIN_EMAIL=admin@test.com

  mysql:
    image: mysql:9.1.0
    environment:
      # CHANGE THESE WHEN BUILDING THE IMAGE FOR PRODUCTION TO MATCH SECRETS
      MYSQL_ROOT_PASSWORD: password
      DB_USERNAME: cms_user
      DB_PASSWORD: password
      DB_DATABASE: cms
    volumes:
      - mysql_linode_prod_data:/var/lib/mysql
      - ./config/mysql/generate_init_sql.sh:/scripts/generate_init_sql.sh
    command: ["/bin/bash", "-c", "chmod +x /scripts/generate_init_sql.sh && /scripts/generate_init_sql.sh && docker-entrypoint.sh mysqld"]

volumes:
  mysql_linode_prod_data:
  willowcms_uploads: