DROP DATABASE IF EXISTS `cms`;
CREATE DATABASE `cms` DEFAULT CHARACTER SET = `utf8mb4` COLLATE = `utf8mb4_unicode_ci`;

CREATE USER 'cms_user'@'localhost' IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON `cms`.* TO 'cms_user'@'localhost';
FLUSH PRIVILEGES;

CREATE USER 'cms_user'@'%' IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON `cms`.* TO 'cms_user'@'%';
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS `cms_test`;
CREATE DATABASE `cms_test` DEFAULT CHARACTER SET = `utf8mb4` COLLATE = `utf8mb4_unicode_ci`;

CREATE USER 'cms_user_test'@'localhost' IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON `cms_test`.* TO 'cms_user_test'@'localhost';
FLUSH PRIVILEGES;

CREATE USER 'cms_user_test'@'%' IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON `cms_test`.* TO 'cms_user_test'@'%';
FLUSH PRIVILEGES;